openstack_username     = "admin"
openstack_password     = "bgyDFHPkFMyogIDSJhCxQg1G4"
openstack_tenant_name  = "admin"
openstack_auth_url     = "https://100.65.247.201:13000"
openstack_domain_name  = "default"
ssh_password           = "Mycl0ud@456"
